Replaced deprecated constants, minor fixes
andersevenrud/ha-nexa-bridge-x pull request #38
Opened 2024-04-01 22:07 UTC by sonite

Invalid color modes & replace deprecated constants

2024-04-01 22:16 UTC, andersevenrud requested changes
Looks good 👍 

But can you separate these ?

2024-04-01 22:16 UTC, andersevenrud commented on custom_components/nexa_bridge_x/entities.py
> +    _attr_supported_color_modes = {ColorMode.BRIGHTNESS}
These changes needs to go into a separate PR and then be verified. Along with dumps of the nodes you have that required these modifications.

2024-04-01 22:16 UTC, andersevenrud commented on README.md
> +![custom_repos](https://github.com/sonite/ha-nexa-bridge/assets/1986942/ed841f07-1815-41cd-a49c-4ff5dd72c675)
Changes to documentation should also be a separate PR.

2024-04-01 22:21 UTC, andersevenrud commented on custom_components/nexa_bridge_x/entities.py
> +    _attr_supported_color_modes = {ColorMode.BRIGHTNESS}
Ideally an issue should be created if there is some kind of issue or required change to underlying entities, etc.

2024-04-01 23:02 UTC, closed without merging

2024-04-01 23:06 UTC, sonite commented
It appears that I'll have to re-fork the repository and make changes file by file, submitting pull requests for each. I can't seem to find an option to edit and split already committed changes. Additionally, GitHub automatically includes all file changes in a commit, so I can't choose which ones to include individually. :(

2024-04-02 12:04 UTC, andersevenrud commented
>It appears that I'll have to re-fork the repository and make changes

Not *really*. You can cherry-pick the changes.

> I can't seem to find an option to edit and split already committed changes

Yeah, it's a bit tricky if not familiar with git.

> GitHub automatically includes all file changes in a commit, so I can't choose which ones to include individually. :(

It requires creating branches for each pull-request. The best way to avoid any problems is to not use the "main" branch.

---

If it's too much then I'll find another way to split this up